### ISSUE TITLE
Failed to build in qt-creator (Ubuntu 12.04)

### ISSUE THREAD

**Issue by deepdivingspearo** [vertcoin/vertcoin-old#3]
Hi Folks,

Tried to build the wallet from source on a Ubuntu 12.04 install.

Expected behaviour, being able to build the wallet from source using qt-creator
What happened, qt-creator failed to build 
- tried to install all dependencies as mentioned in readme but this failed
  "libminiupnpc-dev : Depends: libminiupnpc8 (= 1.6-3ubuntu1) but 1.6-precise2 is to be installed"
- did a git clone
- I was going to build using qt-creator, so went to open "vertcoin-qt.pro" as instructed but only found "bitcoin-qt.pro".
- Tried to build this and it failed with the following "/XXXXX/vertcoin/bitcoin-qt-build-desktop-Qt_4_8_1_in_PATH__System__Release/../vertcoin/src/db.h:14: error: db_cxx.h: No such file or directory"

Am I doing something wrong or is this a bug?

Thanks in advance.

**Comment by erkmos** [comment]
That message means that it can't find the header files for libdb++, did you install the -dev version of libdb++? If you did, you might need to tell qt-creator where to find the files

**Comment by deepdivingspearo** [comment]
Thanks @erkmos. 

Re-installed the libdb++-dev package and it started to build. However it still failed with the following (due to the package in the original bug report not being installed it looks like):

/XXXX/vertcoin/bitcoin-qt-build-desktop-Qt_4_8_1_in_PATH__System__Release/../vertcoin/src/main.cpp:-1: In function 'void VertcoinMiner(CWallet*)':

/XXXX/vertcoin/bitcoin-qt-build-desktop-Qt_4_8_1_in_PATH__System__Release/../vertcoin/src/main.cpp:4691: warning: stack protector not protecting local variables: variable length buffer [-Wstack-protector]

/XXXX/vertcoin/bitcoin-qt-build-desktop-Qt_4_8_1_in_PATH__System__Release/../vertcoin/src/net.cpp:18: error: miniupnpc/miniwget.h: No such file or directory

**Comment by erkmos** [comment]
This time you're missing libminiupnpc-dev. Just do apt-get install libqrencode-dev libminiupnpc-dev 

if it complains about something to do with boost just install libboost-all-dev too

And finally if you get a message about libmemenv.a not found you need to cd to src/leveldb and execute: make libleveldb.a libmemenv.a and then try compiling again

**Comment by deepdivingspearo** [comment]
Thanks again @erkmos. It seems libminiupnpc-dev has a broken dependency in Ubuntu 12.04. Filed a bug > https://bugs.launchpad.net/ubuntu/+source/miniupnpc/+bug/1280060

**Comment by deepdivingspearo** [comment]
This issue was due to a conflict with package versions (a newer version was being supplied via a PPA I use for alt wallets). The package built fine on a 12.04 testing VM I had which was a default/clean install of 12.04.

However it won't run on my desktop. 
"./vertcoin-qt: error while loading shared libraries: libminiupnpc.so.8: wrong ELF class: ELFCLASS64"

Crumbs man. This is way to hard.

**Comment by Paul-Bradley** [comment]
Hmmm, try

sudo apt-get install ia32-libs

I suspect a 32 bit linkinking somewhere in your build, when you are on
a 64 bit OS.

**Comment by deepdivingspearo** [comment]
@Paul-Bradley Thanks for the tip. I had that package installed already, but figured as that might be the issue (a 32/64 problem somewhere) I rebuild the package on a 64bit server I have and it worked.

So the issue is on my own system, not an issue with the current release. 

It's been suggested before, but as a community I think we really should provide builds for releases like Ubuntu 12.04 and the upcoming 14.04 release as they both long term releases. I'm not to worried about getting "down and dirty" like this to get the wallet, but for an average user... they'd be running for the hills.
